=== Firewess/SEUXML/exp2/ANIME_DTD_v1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT animeList (anime*)>
<!ELEMENT anime (name+, images, seasons, priceList)>
<!ATTLIST anime
			id			ID				#REQUIRED
			isfinished	(true | false)	#REQUIRED
			episodeNum	CDATA			#REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name language CDATA #IMPLIED>
<!ELEMENT images (thumbnail, preview+)>
<!ELEMENT thumbnail (#PCDATA)>
<!ATTLIST thumbnail size CDATA #IMPLIED>
<!ELEMENT preview (#PCDATA)>
<!ATTLIST preview size CDATA #IMPLIED>
<!ELEMENT seasons (season*)>
<!ATTLIST seasons currentSeason CDATA "1">
<!ELEMENT season (#PCDATA)>
<!ATTLIST season seasonId IDREF #REQUIRED>
<!ELEMENT priceList (price+)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price 
			platform	(bilibili | tecent | iqiyi | unknown)	"unknown"
			currency	CDATA 	#IMPLIED>

=== Firewess/SEUXML/exp2/example_data_v2(邢铭华).xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animeList SYSTEM "D:\Documents\xml\ANIME_DTD_v1.dtd">
<animeList>
	<anime id="JOJO5" episodeNum="21" isfinished="false">
		<name language="Chinese">JOJO的奇妙冒险 黄金之风</name>
		<images>
			<thumbnail size="100">https://here_pictures_server_path</thumbnail>
			<preview>https://here_pictures_server_path</preview>
		</images>
		<seasons currentSeason="5">
		</seasons>
		<priceList>
			<price currency="Yuan" platform="bilibili">15/month</price>
		</priceList>
	</anime>
</animeList>
